dist: precise

language: php

services:
  - mysql

php:
  - 7.1

git:
  depth: 200

before_install:
  # Create mautictest database
  - mysql -e 'CREATE DATABASE mautictest;'

  # turn off XDebug
  - phpenv config-rm xdebug.ini || return

  # install dependencies in parallel
  - travis_retry composer global require hirak/prestissimo

  # set to test environment for Symfony's commands in post install commands
  - export SYMFONY_ENV="test"

install:
  # There are 2 build variants to be built based on the branch name:
  #
  # build.sh      - Standard Mautic (default)
  #                 Includes latest release and standard dependencies.
  #                 Pretty much just a standard `composer install`.
  #
  # build-dist.sh - Custom distribution (for branches containing the word "dist")
  #                 Includes a specific (recent) sha, core patches, custom theme, and additional plugins.
  #                 This build is Used for advanced testing and deployment by DMS.
  - if [[ "$TRAVIS_BRANCH" = *"dist"* ]]; then ./scripts/build-dist.sh; else bash ./scripts/build.sh; fi

script:
  # Run PHPUnit on the complete build.
  - rm -rf bin/phpunit
#  - cd mautic
#  - bin/phpunit -d memory_limit=2048M --bootstrap vendor/autoload.php --configuration app/phpunit.xml.dist --fail-on-warning --stop-on-failure
#  - cd ../

before_deploy:
  # Travis uses gitignore instead of ebignore https://github.com/travis-ci/dpl/issues/411
  # Overcome this issue by pretending everything has been committed.
  - DESCRIPTION=`git log -n 1 --pretty=%B`
  - find . -name ".gitignore" -print0 | xargs -0 rm -rf
  - cp .ebignore .gitignore
  - git config --global user.email "heathdutton@gmail.com"
  - git config --global user.name "heathdutton"
  - git add -A
  - git commit -m "Surpassing Travis EB incompatibility" --quiet
  # Generate a version label based on git describe and preserve description before above.
  - VERSION=`git describe --always --long`
  - export ELASTIC_BEANSTALK_LABEL="$VERSION"
  - echo "Version label is '$ELASTIC_BEANSTALK_LABEL'"
  - export ELASTIC_BEANSTALK_DESCRIPTION="$DESCRIPTION"
  - echo "Version description is '$ELASTIC_BEANSTALK_DESCRIPTION'"

deploy:
  # Optional deployment to Elastic Beanstalk (Environment Variables must be configured in your Travis settings)
  provider: elasticbeanstalk
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  region: $AWS_REGION
  app: $AWS_EB_APP
  env: $AWS_EB_ENV
  bucket_name: $AWS_S3_BUCKET_NAME
  bucket_path: $AWS_S3_BUCKET_PATH
  skip_cleanup: true
  on:
    branch: dev-dist

# http://docs.travis-ci.com/user/notifications/
notifications:
  slack: dmsgroup:3nPbmvUU584YtdeDVOweIMWg