dist: precise

language: php

services:
  - mysql

php:
  - 7.1

before_install:
  # Create mautictest database
  - mysql -e 'CREATE DATABASE mautictest;'

  # turn off XDebug
  - phpenv config-rm xdebug.ini || return

  # install dependencies in parallel
  - travis_retry composer global require hirak/prestissimo

  # set to test environment for Symfony's commands in post install commands
  - export SYMFONY_ENV="test"

install:
  # There are 2 build variants to be built based on the branch name:
  #
  # build.sh      - Standard Mautic (default)
  #                 Includes latest release and standard dependencies.
  #                 Pretty much just a standard `composer install`.
  #
  # build-dist.sh - Custom distribution (for branches containing the word "dist")
  #                 Includes a specific (recent) sha, core patches, custom theme, and additional plugins.
  #                 This build is Used for advanced testing and deployment by DMS.
  - if [[ "$TRAVIS_BRANCH" = *"dist"* ]]; then ./scripts/build-dist.sh; else bash ./scripts/build.sh; fi

script:
  # Run PHPUnit on the complete build.
  - cd mautic
  - bin/phpunit -d memory_limit=2048M --bootstrap vendor/autoload.php --configuration app/phpunit.xml.dist --fail-on-warning --stop-on-failure
  - cd ../

before_deploy:
  # Generate a version label based on git describe.
  - export ELASTIC_BEANSTALK_LABEL="${git describe --always}"
  - echo "Version to be deployed is '$ELASTIC_BEANSTALK_LABEL'"
  # Prepend the description by the date.
  - DATE=`date '+%Y-%m-%d %H:%M:%S'`;
  - export ELASTIC_BEANSTALK_DESCRIPTION="$DATE - $ELASTIC_BEANSTALK_DESCRIPTION"
  - echo "Build description is '$ELASTIC_BEANSTALK_DESCRIPTION'"

deploy:
  # Optional deployment to Elastic Beanstalk (Environment Variables must be configured in your Travis settings)
  provider: elasticbeanstalk
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  region: $AWS_REGION
  app: $AWS_EB_APP
  env: $AWS_EB_ENV
  bucket_name: $AWS_S3_BUCKET_NAME
  bucket_path: $AWS_S3_BUCKET_PATH
  skip_cleanup: true
  on:
    branch: dev-dist

# http://docs.travis-ci.com/user/notifications/
notifications:
  slack: dmsgroup:3nPbmvUU584YtdeDVOweIMWg
