dist: precise

language: php

services:
  - mysql

php:
  - 7.1

before_install:
  # Create mautictest database
  - mysql -e 'CREATE DATABASE mautictest;'

  # turn off XDebug
  - phpenv config-rm xdebug.ini || return

  # install dependencies in parallel
  - travis_retry composer global require hirak/prestissimo

  # set to test environment for Symfony's commands in post install commands
  - export SYMFONY_ENV="test"

# Uncomment the version you wish to install:
install:

  # Standard Mautic (latest released version and dependencies)
  # - bash ./scripts/dist-standard.sh

  # Custom Mautic (Custom sha, theme, plugins and patches used by DMS)
  - bash ./scripts/dist-custom.sh

script:

  # Go to mautic root.
  - cd mautic

  # Run PHPUnit
  - bin/phpunit -d memory_limit=2048M --bootstrap vendor/autoload.php --configuration app/phpunit.xml.dist --fail-on-warning --debug --stop-on-failure

deploy:

  provider: elasticbeanstalk
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  region: $AWS_REGION
  app: $AWS_EB_APP
  env: $AWS_EB_ENV
  bucket_name: $AWS_S3_BUCKET_NAME
  bucket_path: $AWS_S3_BUCKET_PATH